In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


In [20]:
#1. Concatenate two arrays arr1 and arr2 horizontally (side by side) using np.concatenate().
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 = arr1.reshape((1, arr1.shape[0]))
arr2 = arr2.reshape((1, arr2.shape[0]))
arr1
arr2


array([[4, 5, 6]])

In [21]:
np.concatenate([arr1,arr2],axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
#2. Concatenate two arrays arr1 and arr2 vertically (stacked on top of each other) using np.concatenate().
np.concatenate((arr1,arr2),axis=0)


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#3. Create to series s1:(1,2,3) s2:(4,5,6) and concatenate them horizontally (side by side) using pd.concat().
ser1 = Series([1, 2, 3])
ser2 = Series([4, 5, 6])
pd.concat([ser1, ser2], axis=1)

0  1
0  1  4
1  2  5
2  3  6

In [27]:
#4. Concatenate two series s1 and s2 vertically (stacked on top of each other) using pd.concat().
pd.concat([ser1, ser2], axis=0)


0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

In [28]:
#5. Create two data frames df1: {'A': [1, 2, 3], 'B': [4, 5, 6]}, df2: {'C': [7, 8, 9], 'D': [10, 11, 12]} and concatenate them horizontally (side by side) using pd.concat().
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'C': [7, 8, 9], 'D': [10, 11, 12]})
pd.concat([df1, df2], axis=1)

A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [29]:
#6. Concatenate two data frames df1 and df2 vertically (stacked on top of each other) using pd.concat().
pd.concat([df1, df2], axis=1)

A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [32]:
#7.Concatenate two data frames df1 and df2 horizontally (side by side) using df1.join(df2).
df1.join(df2)

A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [33]:
#8. Concatenate two data frames df1 and df2 vertically (stacked on top of each other) using df1.append(df2).
df1.append(df2)

C:\Users\Mariya\AppData\Local\Temp\ipykernel_25564\1791801005.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
0  NaN  NaN  7.0  10.0
1  NaN  NaN  8.0  11.0
2  NaN  NaN  9.0  12.0

C:\Users\Mariya\AppData\Local\Temp\ipykernel_25564\2995832154.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
0  NaN  NaN  7.0  10.0
1  NaN  NaN  8.0  11.0
2  NaN  NaN  9.0  12.0

In [34]:
#9. Concatenate two data frames df1 and df2 vertically (stacked on top of each other) and reset the index using pd.concat() and the argument ignore_index=True.
pd.concat([df1, df2], ignore_index=True)


A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
3  NaN  NaN  7.0  10.0
4  NaN  NaN  8.0  11.0
5  NaN  NaN  9.0  12.0

In [36]:
#10. Concatenate two data frames df1 and df2 vertically (stacked on top of each other) and add a multi-level index using pd.concat() and the argument keys=['df1', 'df2'].
pd.concat([df1, df2], keys=['df1', 'df2'])


A    B    C     D
df1 0  1.0  4.0  NaN   NaN
    1  2.0  5.0  NaN   NaN
    2  3.0  6.0  NaN   NaN
df2 0  NaN  NaN  7.0  10.0
    1  NaN  NaN  8.0  11.0
    2  NaN  NaN  9.0  12.0